/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2020-07-11 20:19:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class actualizar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1594444498490L));
    _jspx_dependants.put("jar:file:/C:/Users/Dange/OneDrive/Escritorio/proyectito/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/asesoramientoSoftware/WEB-INF/lib/standard.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1098729090000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("  \t\t<form method=\"post\" action=\"\" method=\"post\" id=\"id_registrar\">\r\n");
      out.write("  \t\t <input type=\"hidden\" id=\"idCriticidad\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requerimiento.criticidad}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t    <label for=\"exampleFormControlTextarea1\">Codigo</label>\r\n");
      out.write("\t\t\t    <input type=\"text\" class=\"form-control\" id=\"exampleFormControlTextarea1\" name=\"codigo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requerimiento.codigo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Ingresar descripcion\" rows=\"3\" >\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t    <label for=\"exampleFormControlTextarea1\">Descripcion</label>\r\n");
      out.write("\t\t\t    <input type=\"text\" class=\"form-control\" id=\"exampleFormControlTextarea1\" name=\"descripcion\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requerimiento.descripcion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Ingresar descripcion\" rows=\"3\" >\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t    <label for=\"exampleFormControlTextarea1\">Origen</label>\r\n");
      out.write("\t\t\t    <input type=\"text\" class=\"form-control\" id=\"exampleFormControlTextarea1\" name=\"origen\" placeholder=\"Ingresar origen\" rows=\"3\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requerimiento.origen}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t    <label for=\"exampleFormControlTextarea1\">Area</label>\r\n");
      out.write("\t\t\t    <input type=\"text\" class=\"form-control\" id=\"exampleFormControlTextarea1\" name=\"area\" placeholder=\"Ingresar area\" rows=\"3\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requerimiento.area}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t    <label for=\"exampleFormControlSelect1\">Criticidad</label>\r\n");
      out.write("\t\t\t    <select class=\"form-control\" name=\"criticidad\" id=\"idcriticidad\">\r\n");
      out.write("\t\t\t      <option>[Seleccione]</option>\r\n");
      out.write("\t\t\t      <option value=\"Necesario\">Necesario</option>\r\n");
      out.write("\t\t\t      <option value=\"Importante\">Importante</option>\r\n");
      out.write("\t\t\t       <option value=\"Deseado\">Deseado</option>\r\n");
      out.write("\t\t\t    </select>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"form-check form-check-inline\">\r\n");
      out.write("\t\t\t\t  <input class=\"form-check-input\" type=\"radio\" name=\"estado\" id=\"inlineRadio1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requerimiento.estado}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" >\r\n");
      out.write("\t\t\t\t  <label class=\"form-check-label\" for=\"inlineRadio1\">Terminado</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-check form-check-inline\">\r\n");
      out.write("\t\t\t\t  <input class=\"form-check-input\" type=\"radio\" name=\"estado\" id=\"inlineRadio2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requerimiento.estado}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t  <label class=\"form-check-label\" for=\"inlineRadio2\">En proceso</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-check form-check-inline\">\r\n");
      out.write("\t\t\t\t  <input class=\"form-check-input\" type=\"radio\" name=\"estado\" id=\"inlineRadio3\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requerimiento.estado}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t  <label class=\"form-check-label\" for=\"inlineRadio3\">Pendiente</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t  <button type=\"button\" class=\"btn btn-primary\">Actualizar</button>\r\n");
      out.write("\t\t  <button type=\"button\" class=\"btn btn-warning\">Eliminar</button>\r\n");
      out.write("\t\t  <button type=\"button\" class=\"btn btn-success\">Listar</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Optional JavaScript -->\r\n");
      out.write("    <!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write(" \r\n");
      out.write(" \t<!-- jQuery validate -->\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/jquery-validation@1.19.1/dist/jquery.validate.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/jquery-validation@1.19.1/dist/jquery.validate.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/jquery-validation@1.19.1/dist/additional-methods.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/jquery-validation@1.19.1/dist/additional-methods.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(\".btn-primary\").click(function(){\r\n");
      out.write("\t\t$(\"#id_registrar\").attr(\"action\",\"ServletRequerimiento?accion=ACTUALIZAR\");\r\n");
      out.write("\t\tid_registrar.submit();\r\n");
      out.write("\t})\r\n");
      out.write("\t$(\".btn-warning\").click(function(){\r\n");
      out.write("\t\t$(\"#id_registrar\").attr(\"action\",\"ServletRequerimiento?accion=ELIMINAR\");\r\n");
      out.write("\t\tid_registrar.submit();\r\n");
      out.write("\t})\r\n");
      out.write("\t$(\".btn-success\").click(function(){\r\n");
      out.write("\t\twindow.location.href='lista.jsp';\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#idcriticidad\").val($(\"#idCriticidad\").val());\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("  \t\r\n");
      out.write("  <script>    \r\n");
      out.write("\t  $('#id_registrar').validate({\r\n");
      out.write("\t    rules: {\r\n");
      out.write("\t    \tcodigo:{\r\n");
      out.write("\t    \t\trequired:true,\r\n");
      out.write("\t    \t},\r\n");
      out.write("\t    \tdescripcion:{\r\n");
      out.write("\t    \t\trequired:true,\r\n");
      out.write("\t    \t\tpattern:'[a-zA-Z\\\\s\\\\Ñ\\\\ñ]{1,200}'\r\n");
      out.write("\t    \t},\r\n");
      out.write("\t    \torigen:{\r\n");
      out.write("\t    \t\trequired:true,\r\n");
      out.write("\t    \t\tpattern:'[a-zA-Z\\\\s\\\\Ñ\\\\ñ]{1,200}'\r\n");
      out.write("\t    \t},\r\n");
      out.write("\t    \tarea:{\r\n");
      out.write("\t    \t\trequired:true,\r\n");
      out.write("\t    \t\tpattern:'[a-zA-Z\\\\s\\\\Ñ\\\\ñ]{1,200}'\r\n");
      out.write("\t    \t},\r\n");
      out.write("\t    \tcriticidad:{\r\n");
      out.write("\t    \t\trequired:true\r\n");
      out.write("\t    \t},\r\n");
      out.write("\t    \testado:{\r\n");
      out.write("\t    \t\trequired:true\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    },\r\n");
      out.write("\t    messages:{\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tcodigo:{\r\n");
      out.write("\t    \t\trequired:'Ingresar nombre',\r\n");
      out.write("\t    \t},\r\n");
      out.write("\t    \tdescripcion:{\r\n");
      out.write("\t    \t\trequired:'Ingresar nombre',\r\n");
      out.write("\t    \t\tpattern:'Campo descripcion solo letras'\r\n");
      out.write("\t    \t},\r\n");
      out.write("\t    \torigen:{\r\n");
      out.write("\t    \t\trequired:'ingresar apellido',\r\n");
      out.write("\t    \t\tpattern:'Campo origen solo letras'\r\n");
      out.write("\t    \t},\r\n");
      out.write("\t    \tarea:{\r\n");
      out.write("\t    \t\trequired:'ingresar edad',\r\n");
      out.write("\t    \t\tpattern:'Campo area solo letras'\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \t},\r\n");
      out.write("\t    \tcriticidad:{\r\n");
      out.write("\t    \t\trequired:'ingresar criticidad'\r\n");
      out.write("\t    \t},\r\n");
      out.write("\t    \testado:{\r\n");
      out.write("\t    \t\trequired:'ingresar estado'\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    },\r\n");
      out.write("\t    errorElement: 'span',\r\n");
      out.write("\t    errorPlacement: function (error, element) {\r\n");
      out.write("\t        error.addClass('invalid-feedback');\r\n");
      out.write("\t        element.closest('.form-group').append(error);\r\n");
      out.write("\t    },\r\n");
      out.write("\t    highlight: function (element, errorClass, validClass) {\r\n");
      out.write("\t        $(element).addClass('is-invalid');\r\n");
      out.write("\t    },\r\n");
      out.write("\t    unhighlight: function (element, errorClass, validClass) {\r\n");
      out.write("\t        $(element).removeClass('is-invalid');\r\n");
      out.write("\t    },\r\n");
      out.write("\t})\r\n");
      out.write("\t</script>\t\t\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /actualizar.jsp(13,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.MENSAJE!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<div class=\"alert alert-warning alert-dismissible fade show\" role=\"alert\">\r\n");
          out.write("\t\t  <strong>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.MENSAJE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</strong>\r\n");
          out.write("\t\t  <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">\r\n");
          out.write("\t\t    <span aria-hidden=\"true\">&times;</span>\r\n");
          out.write("\t\t  </button>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
